spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/seckill?characterEncoding=utf8&serverTimezone=Hongkong&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 100
      max-lifetime: 1800000
      connection-timeout: 500
      login-timeout: 500
      validation-timeout: 1000
      initialization-fail-timeout: 1000
      connection-test-query: select 1

  #redis7
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis123
    # 连接超时时间（毫秒）
    timeout: 50000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 4
  cache:
    type: redis  #spring-boot-starter-cache 配置缓存类型redis
    redis:
      time-to-live: 90000 #单位毫秒 -1不过期
      key-prefix: CACHE_  #缓存前缀
      use-key-prefix: true #是否启用缓存前缀
      cache-null-values: true #是否缓存空值,true缓存-->防止缓存穿透


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql打印
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seckill.beans.po
  global-config:
    db-config:
      id-type: assign_id